### ISSUE TITLE
The result is not correct when the byte length > 55

### ISSUE THREAD

**Issue by stonexing** [julioflspbr/swift-cypher#4]
`MD5 ("executesyourkernelfunctionoverabcexecutesyourkernelfunc") = fda9bd4b440550d9a8f3907a36a292df`

`executesyourkernelfunctionoverabcexecutesyourkernelfunc 
executesyourkernelfunctionoverabcexecutesyourkernelfunct `
I can get contact result with first string.
But I can not get right result with second string.

**Comment by stonexing** [comment]
After many times test. I find this project can get right md5 when bytes length <= 55;
The result is not right when the bytes length > 55.

**Comment by julioflspbr** [comment]
Hi @stonexing great finding!

So, this was a discovery test of how powerful the Metal is to execute things other than shading, So my personal purpose with this project is done.

However, I am happy that you found this bug! Now, do you accept the challenge of finding the fit solution for this problem? It's your turn.

**Comment by stonexing** [comment]
Thank you for response.
I have already work out with the right result.
I rewrite code base on your code and another c++ open source project https://github.com/JieweiWei/md5
It's easy to add "thread" or "constant" or "device" according you code sample.
Now it's work great.
